# helm/kube-state-metrics/values-staging.yaml

replicaCount: 2

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5